### ISSUE TITLE
Updating broke the game

### ISSUE THREAD

**Issue by WizardSteak107** [Booplicate/MAS-Submods-SubmodUpdaterPlugin#10]
I tried to use the ingame submode updater and the game couldn't open and i dont know how to fix it. please help me, Thank you.
[traceback.txt](https://github.com/Booplicate/MAS-Submods-SubmodUpdaterPlugin/files/7741456/traceback.txt)

**Comment by Booplicate** [comment]
Looks like it's not updating that broke it. RenPy couldn't properly compile the scripts, you'll need to delete `Den.rpyc` and let it recompile.

**Comment by WizardSteak107** [comment]
Where do i delete it from?

**Comment by WizardSteak107** [comment]
Thank you so much!
