### ISSUE TITLE
I get an error every time I try to open the plugin.

### ISSUE THREAD

**Issue by talusiana** [Booplicate/MAS-Submods-SubmodUpdaterPlugin#12]
I installed it the way I did with any other submod, is there something I should've kept in mind? Here's the full traceback >
[traceback.txt](https://github.com/Booplicate/MAS-Submods-SubmodUpdaterPlugin/files/9183774/traceback.txt)

Okay so, I thought it was a submod, but even when I put it in the main directory, it's still not working for me

**Comment by Booplicate** [comment]
It looks like the issue is in `kventis_rpc`, it doesn't define the screen it tries to use. You can report that to the creator of the submod.
