### ISSUE TITLE
error when accessing the submod menue

### ISSUE THREAD

**Issue by Incognito-100** [Booplicate/MAS-Submods-SubmodUpdaterPlugin#14]
[traceback.txt](https://github.com/Booplicate/MAS-Submods-SubmodUpdaterPlugin/files/9446207/traceback.txt)

**Comment by Booplicate** [comment]
One of the submods you have installed is using invalid semantic version, which they could fix by either making their github tags of the appropriate format, or using a custom `tag_formatter`. This is [documented](https://github.com/Booplicate/MAS-Submods-SubmodUpdaterPlugin#some-important-notes), it's not a bug in the updeter.
