### ISSUE TITLE
After Launching MAS, I am unable to update custom rooms from v1.01 to v1.02 using the submod updater plugin

### ISSUE THREAD

**Issue by delongr28** [Booplicate/MAS-Submods-SubmodUpdaterPlugin#5]
MAS plays as per normal and the custom backgrounds do load in, I am just unable to update them from v1.01 to v1.02 using the submod updater plugin despite being notified there's an update.

![2](https://user-images.githubusercontent.com/16112887/94891354-67618200-04b4-11eb-8cdf-6589a93370b5.png)

![3](https://user-images.githubusercontent.com/16112887/94891366-6deff980-04b4-11eb-8450-2ddd506f52c2.png)

Here's the log I think it's talking about:
[log.txt](https://github.com/Booplicate/MAS-Submods-SubmodUpdaterPlugin/files/5316154/log.txt)

Or it's this one:
[mas_log.txt](https://github.com/Booplicate/MAS-Submods-SubmodUpdaterPlugin/files/5316155/mas_log.txt)

PS: I posted this on https://github.com/tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository/issues/10 as well, am unsure if this error is with the submodupdater plugin or the tw4449 Custom Room submod itself.

**Comment by Booplicate** [comment]
I wasn't able to reproduce the issue myself, and I see that you were able to update other submods, it's only 3 that got errors. I think the problem may be in those. That, or it's because you're using steam. It's recommended to run standalone DDLC for mods.
