### ISSUE TITLE
Error when trying to update submods

### ISSUE THREAD

**Issue by ThatOneUsername343** [Booplicate/MAS-Submods-SubmodUpdaterPlugin#6]
My game says that some of my submods have updates, but when I try to update them I always get an error. It says check the log for details, but I'm not sure which log it is referring to and I wouldn't know what to look for even if I knew which log it was. Any way I can fix this error?

**Comment by Booplicate** [comment]
Send your `submod_log.txt`, it's in the `/log` folder. Actually, send `mas_log.txt` too.

**Comment by ThatOneUsername343** [comment]
[submod_log.txt](https://github.com/Booplicate/MAS-Submods-SubmodUpdaterPlugin/files/5803852/submod_log.txt)
[mas_log.txt](https://github.com/Booplicate/MAS-Submods-SubmodUpdaterPlugin/files/5803855/mas_log.txt)

**Comment by Booplicate** [comment]
Try the latest release for SUP.
