### ISSUE TITLE
"An exception has occurred." whenever I press the submod button in menu

### ISSUE THREAD

**Issue by cakey-yb** [Booplicate/MAS-Submods-SubmodUpdaterPlugin#7]
This is the latest version. I showed it to my techy friend and they said:
_"it looks like the program expected some version like '1.2.3'
but it got something more like 'v1.2.3'
which if the computer is expecting a number isn't going to work"_

[traceback.txt](https://github.com/Booplicate/MAS-Submods-SubmodUpdaterPlugin/files/6046805/traceback.txt)

**Comment by Booplicate** [comment]
Send `submod_log.txt` please.

**Comment by cakey-yb** [comment]
[submod_log.txt](https://github.com/Booplicate/MAS-Submods-SubmodUpdaterPlugin/files/6051811/submod_log.txt)

**Comment by Booplicate** [comment]
What is that `Panic Button` submod?

**Comment by Booplicate** [comment]
I see the issue, it's a bug in that submod. You may want to report it to its author.

There's actually 2 bugs. One has been reported in the log:
> Failed to parse JSON data: attachment with id '0' doesn't exist. Submod: 'Panic Button'.

**Comment by cakey-yb** [comment]
Ah ic. I got it from here: https://www.reddit.com/r/MASFandom/comments/lrvuj0/mas_panic_button_submod/?utm_source=share&utm_medium=web2x&context=3 
I'll comment on the author's submod, thanks
