### ISSUE TITLE
getting error for submod

### ISSUE THREAD

**Issue by At1619** [Booplicate/MAS-Submods-SubmodUpdaterPlugin#8]
![image](https://user-images.githubusercontent.com/89611432/131228682-0e9c451c-6198-4266-8533-87645dcc1039.png)

Getting this error on submod logs. Is there any way to fix this.

**Comment by At1619** [comment]
Also im getting that error for every submod that is supposed to be compatible with the plugin.


![image](https://user-images.githubusercontent.com/89611432/131233885-c62b7c32-75c2-4337-b0ad-078572cb8aa6.png)

**Comment by Booplicate** [comment]
Unsure, but looks like this error is from the outer scope. Make sure you installed the `ssl` and `_ssl` packages, too.

![Capture](https://user-images.githubusercontent.com/53382877/131246344-6b90f2ae-4564-41a9-b564-f4fd823a8ee4.PNG)

**Comment by aatifthameem** [comment]
Where are they supposed to be installed at? Also where they inside the game folder of the submod?

**Comment by At1619** [comment]
Ah I see my mistake, I didnt copy the folder named lib when I added the submod, added that folder and checked submod logs and the error is not there anymore. Thanks for your help
